version: '3.9'

services:
  chamazetu_database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chamazetu_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  message_broker:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    environment:
      - TZ=Africa/Nairobi

  chamazetu_frontend_database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${FRONTEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FRONTEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${FRONTEND_POSTGRES_DB}
    volumes:
      - frontend_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  chamazetu_frontend:
    build:
      context: ./frontend_chamazetu
    command: python manage.py runsslserver 0.0.0.0:8000 --certificate /app/frontend/cert.pem --key /app/frontend/key.pem
    volumes:
      - ./frontend_chamazetu:/app/frontend/
      - ./staticfiles:/app/frontend/staticfiles
      - ./app/frontend/certs:/app/frontend/certs
    ports:
      - "8000:8000"
    depends_on:
      - chamazetu_frontend_database
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${FRONTEND_POSTGRES_USER}:${FRONTEND_POSTGRES_PASSWORD}@chamazetu_frontend_database:5432/${FRONTEND_POSTGRES_DB}

  chamazetu_backend:
    build:
      context: ./backend_chamazetu
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --reload
    volumes:
      - ./backend_chamazetu:/app/backend/
    ports:
      - "9400:9400"
    depends_on:
      - chamazetu_database
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@chamazetu_database:5432/${POSTGRES_DB}

  celery_worker:
    build:
      context: ./frontend_chamazetu
    command: celery -A frontend_chamazetu.celery worker --pool=solo -l INFO
    volumes:
      - ./frontend_chamazetu:/app/frontend/
    depends_on:
      - chamazetu_frontend_database
      - message_broker
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${FRONTEND_POSTGRES_USER}:${FRONTEND_POSTGRES_PASSWORD}@chamazetu_frontend_database:5432/${FRONTEND_POSTGRES_DB}

  celery_beat_scheduler:
    build:
      context: ./frontend_chamazetu
    command: celery -A frontend_chamazetu.celery beat -l INFO
    volumes:
      - ./frontend_chamazetu:/app/frontend/
    depends_on:
      - chamazetu_frontend_database
      - message_broker
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${FRONTEND_POSTGRES_USER}:${FRONTEND_POSTGRES_PASSWORD}@chamazetu_frontend_database:5432/${FRONTEND_POSTGRES_DB}

volumes:
  redis_data:
  chamazetu_data:
  frontend_data:
