# 6832869ee948_table_banking_v1_tables_08_nov_24.py
                                                                                                                                                                                             
"""table banking v1 tables 08-nov-24                                                                                                                                                                                             
                                                                                                                                                                                                                                 
Revision ID: 6832869ee948                                                                                                                                                                                                        
Revises: 5a0565dc8b5f                                                                                                                                                                                                            
Create Date: 2024-11-08 16:55:36.286633                                                                                                                                                                                          
                                                                                                                                                                                                                                 
"""

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###                                                                                                                                                                
    op.drop_index('ix_chama_contribution_day_id', table_name='chama_contribution_day')
    op.drop_table('chama_contribution_day')
    op.add_column('activities', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('activity_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('activity_contribution_dates', sa.Column('activity_is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'user_id', existing_type=sa.VARCHAR(), nullable=False)
    op.add_column('activities_users', sa.Column('user_is_active', sa.Boolean(), nullable=True))
    op.add_column('activities_users', sa.Column('activity_is_active', sa.Boolean(), nullable=True))
    op.add_column('activities_users', sa.Column('activity_is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('activities_users', 'is_active')
    op.drop_column('activities_users', 'is_deleted')
    op.add_column('table_banking_loan_management', sa.Column('unpaid_interest', sa.Float(), nullable=True, server_default='0'))
    op.alter_column('table_banking_loan_management', 'unpaid_interest', nullable=False, server_default=None)
    op.add_column('table_banking_loan_management', sa.Column('paid_interest', sa.Float(), nullable=True, server_default='0'))
    op.alter_column('table_banking_loan_management', 'paid_interest', nullable=False, server_default=None)
    op.add_column('table_banking_requested_loans', sa.Column('rejected', sa.Boolean(), nullable=True, server_default='False'))
    op.alter_column('table_banking_requested_loans', 'rejected', nullable=False, server_default=None)
    # ### end Alembic commands ###  


def downgrade() -> None:
    op.drop_column('table_banking_requested_loans', 'rejected')
    op.drop_column('table_banking_loan_management', 'paid_interest')
    op.drop_column('table_banking_loan_management', 'unpaid_interest')
    op.add_column('activities_users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('activities_users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('activities_users', 'activity_is_deleted')
    op.drop_column('activities_users', 'activity_is_active')
    op.drop_column('activities_users', 'user_is_active')
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('activity_contribution_dates', 'activity_is_active')
    op.drop_column('activity_accounts', 'is_deleted')
    op.drop_column('activities', 'deleted_at')
    op.create_table('chama_contribution_day',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chama_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_contribution_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name='chama_contribution_day_chama_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chama_contribution_day_pkey')
    )
    op.create_index('ix_chama_contribution_day_id', 'chama_contribution_day', ['id'], unique=False)
