"""updating chamas table

Revision ID: 007b22a34261
Revises: e1bd05e60308
Create Date: 2024-03-13 11:13:49.170025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007b22a34261'
down_revision: Union[str, None] = 'e1bd05e60308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamas', sa.Column('num_of_members_allowed', sa.String(), nullable=False))
    op.add_column('chamas', sa.Column('registration_fee', sa.Integer(), nullable=False))
    op.add_column('chamas', sa.Column('contribution_amount', sa.Integer(), nullable=False))
    op.add_column('chamas', sa.Column('contribution_interval', sa.String(), nullable=False))
    op.add_column('chamas', sa.Column('accepting_members', sa.Boolean(), nullable=True))
    op.add_column('chamas', sa.Column('start_cycle', sa.DateTime(), nullable=False))
    op.add_column('chamas', sa.Column('end_cycle', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamas', 'end_cycle')
    op.drop_column('chamas', 'start_cycle')
    op.drop_column('chamas', 'accepting_members')
    op.drop_column('chamas', 'contribution_interval')
    op.drop_column('chamas', 'contribution_amount')
    op.drop_column('chamas', 'registration_fee')
    op.drop_column('chamas', 'num_of_members_allowed')
    # ### end Alembic commands ###
