"""accepting members

Revision ID: 00a80c6f3e87
Revises: 3bf2ef0dd324
Create Date: 2024-03-28 13:49:21.363664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a80c6f3e87'
down_revision: Union[str, None] = '3bf2ef0dd324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamas', 'accepting_members',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamas', 'accepting_members',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
