"""paybill changed

Revision ID: 01dc0d66896d
Revises: 7a45b3b6352d
Create Date: 2024-05-14 13:14:29.005648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dc0d66896d'
down_revision: Union[str, None] = '7a45b3b6352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_chama', 'paybill_account_number')
    op.add_column('chamas', sa.Column('account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamas', 'account_name')
    op.add_column('about_chama', sa.Column('paybill_account_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
