"""make the names required

Revision ID: 0753a88f1cde
Revises: 144b1dbb5232
Create Date: 2024-04-08 06:23:37.210003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0753a88f1cde'
down_revision: Union[str, None] = '144b1dbb5232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('managers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('managers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('managers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
