"""new investment tables

Revision ID: 119d3f6a3f97
Revises: 0753a88f1cde
Create Date: 2024-04-10 15:26:36.480975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '119d3f6a3f97'
down_revision: Union[str, None] = '0753a88f1cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_invested', sa.Integer(), nullable=False),
    sa.Column('investment_start_date', sa.DateTime(), nullable=False),
    sa.Column('investment_name', sa.String(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_performance_id'), 'investments_performance', ['id'], unique=False)
    op.create_table('money_market_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('current_int_rate', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_market_fund_id'), 'money_market_fund', ['id'], unique=False)
    op.add_column('investments', sa.Column('min_invest_amount', sa.Integer(), nullable=False))
    op.add_column('investments', sa.Column('investment_active', sa.Boolean(), nullable=True))
    op.alter_column('investments', 'investment_rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('investments', 'investment_return',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('investments', 'investment_status')
    op.drop_column('investments', 'investment_end_date')
    op.drop_column('investments', 'investment_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('investment_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('investments', sa.Column('investment_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('investments', sa.Column('investment_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('investments', 'investment_return',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('investments', 'investment_rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('investments', 'investment_active')
    op.drop_column('investments', 'min_invest_amount')
    op.drop_index(op.f('ix_money_market_fund_id'), table_name='money_market_fund')
    op.drop_table('money_market_fund')
    op.drop_index(op.f('ix_investments_performance_id'), table_name='investments_performance')
    op.drop_table('investments_performance')
    # ### end Alembic commands ###
