"""add names to member and manager

Revision ID: 144b1dbb5232
Revises: e0271b4764b2
Create Date: 2024-04-08 06:10:48.878494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144b1dbb5232'
down_revision: Union[str, None] = 'e0271b4764b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('managers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('members', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('members', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'last_name')
    op.drop_column('members', 'first_name')
    op.drop_column('managers', 'last_name')
    op.drop_column('managers', 'first_name')
    # ### end Alembic commands ###
