"""destination column added to wallets

Revision ID: 17607b832ff3
Revises: 506c77a9b5d9
Create Date: 2024-04-18 12:44:07.725795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17607b832ff3'
down_revision: Union[str, None] = '506c77a9b5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('transaction_destination', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'transaction_destination')
    # ### end Alembic commands ###
