"""mmf date addition

Revision ID: 20e0f4327d63
Revises: 9df7b8b52e25
Create Date: 2024-04-11 08:03:39.636216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e0f4327d63'
down_revision: Union[str, None] = '9df7b8b52e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_market_fund', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money_market_fund', 'transaction_date')
    # ### end Alembic commands ###
