"""withdrawal table added

Revision ID: 288dba193c1e
Revises: 719e2f4c8f43
Create Date: 2024-06-16 11:50:06.158483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288dba193c1e'
down_revision: Union[str, None] = '719e2f4c8f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chama_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('withdrawal_date', sa.DateTime(), nullable=False),
    sa.Column('withdrawal_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chama_withdrawals_id'), 'chama_withdrawals', ['id'], unique=False)
    op.alter_column('available_investments', 'min_withdrawal_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_investments', 'min_withdrawal_amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_chama_withdrawals_id'), table_name='chama_withdrawals')
    op.drop_table('chama_withdrawals')
    # ### end Alembic commands ###
