"""removed end cycle and replace with restart

Revision ID: 2c3368612087
Revises: a1166a2d2eda
Create Date: 2024-04-03 05:55:00.122241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c3368612087'
down_revision: Union[str, None] = 'a1166a2d2eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamas', sa.Column('restart', sa.Boolean(), nullable=True))
    op.drop_column('chamas', 'end_cycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamas', sa.Column('end_cycle', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('chamas', 'restart')
    # ### end Alembic commands ###
