"""first supabase tables

Revision ID: 339116fca7d5
Revises: 
Create Date: 2024-05-26 01:04:06.150494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339116fca7d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_name', sa.String(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('min_invest_amount', sa.Integer(), nullable=False),
    sa.Column('investment_period', sa.Integer(), nullable=False),
    sa.Column('investment_period_unit', sa.String(), nullable=False),
    sa.Column('investment_rate', sa.Float(), nullable=False),
    sa.Column('investment_start_date', sa.DateTime(), nullable=True),
    sa.Column('investment_return', sa.Float(), nullable=False),
    sa.Column('investment_returned', sa.Boolean(), nullable=True),
    sa.Column('investment_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_investments_id'), 'available_investments', ['id'], unique=False)
    op.create_table('manager_updates_and_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('feature_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_updates_and_features_id'), 'manager_updates_and_features', ['id'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_table('member_updates_and_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('feature_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_updates_and_features_id'), 'member_updates_and_features', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('wallet_balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_name', sa.String(), nullable=False),
    sa.Column('chama_type', sa.String(), nullable=False),
    sa.Column('num_of_members_allowed', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('registration_fee', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Integer(), nullable=False),
    sa.Column('contribution_interval', sa.String(), nullable=False),
    sa.Column('contribution_day', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('accepting_members', sa.Boolean(), nullable=False),
    sa.Column('start_cycle', sa.DateTime(), nullable=False),
    sa.Column('restart', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('verified_chama', sa.Boolean(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('fine_per_share', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamas_chama_name'), 'chamas', ['chama_name'], unique=True)
    op.create_index(op.f('ix_chamas_id'), 'chamas', ['id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_completed', sa.Boolean(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('transaction_destination', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_table('about_chama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('mission', sa.String(length=500), nullable=True),
    sa.Column('vision', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_chama_id'), 'about_chama', ['id'], unique=False)
    op.create_table('chama_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('account_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chama_accounts_id'), 'chama_accounts', ['id'], unique=False)
    op.create_table('chama_contribution_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('next_contribution_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chama_contribution_day_id'), 'chama_contribution_day', ['id'], unique=False)
    op.create_table('chama_investment',
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('available_investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['available_investment_id'], ['available_investments.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], )
    )
    op.create_table('daily_mmf_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('date_earned', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_mmf_interest_id'), 'daily_mmf_interest', ['id'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('fine', sa.Integer(), nullable=False),
    sa.Column('fine_reason', sa.String(), nullable=False),
    sa.Column('fine_date', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_id'), 'fines', ['id'], unique=False)
    op.create_table('investments_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_invested', sa.Integer(), nullable=False),
    sa.Column('investment_start_date', sa.DateTime(), nullable=False),
    sa.Column('investment_name', sa.String(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('total_interest_earned', sa.Float(), nullable=False),
    sa.Column('weekly_interest', sa.Float(), nullable=False),
    sa.Column('daily_interest', sa.Float(), nullable=False),
    sa.Column('monthly_interest', sa.Float(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_performance_id'), 'investments_performance', ['id'], unique=False)
    op.create_table('members_chamas',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('num_of_shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], )
    )
    op.create_table('money_market_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('current_int_rate', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_market_fund_id'), 'money_market_fund', ['id'], unique=False)
    op.create_table('monthly_mmf_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('total_amount_invested', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_mmf_interest_id'), 'monthly_mmf_interest', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('date_of_transaction', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_completed', sa.Boolean(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('transaction_origin', sa.String(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_monthly_mmf_interest_id'), table_name='monthly_mmf_interest')
    op.drop_table('monthly_mmf_interest')
    op.drop_index(op.f('ix_money_market_fund_id'), table_name='money_market_fund')
    op.drop_table('money_market_fund')
    op.drop_table('members_chamas')
    op.drop_index(op.f('ix_investments_performance_id'), table_name='investments_performance')
    op.drop_table('investments_performance')
    op.drop_index(op.f('ix_fines_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_daily_mmf_interest_id'), table_name='daily_mmf_interest')
    op.drop_table('daily_mmf_interest')
    op.drop_table('chama_investment')
    op.drop_index(op.f('ix_chama_contribution_day_id'), table_name='chama_contribution_day')
    op.drop_table('chama_contribution_day')
    op.drop_index(op.f('ix_chama_accounts_id'), table_name='chama_accounts')
    op.drop_table('chama_accounts')
    op.drop_index(op.f('ix_about_chama_id'), table_name='about_chama')
    op.drop_table('about_chama')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_chamas_id'), table_name='chamas')
    op.drop_index(op.f('ix_chamas_chama_name'), table_name='chamas')
    op.drop_table('chamas')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_member_updates_and_features_id'), table_name='member_updates_and_features')
    op.drop_table('member_updates_and_features')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_manager_updates_and_features_id'), table_name='manager_updates_and_features')
    op.drop_table('manager_updates_and_features')
    op.drop_index(op.f('ix_available_investments_id'), table_name='available_investments')
    op.drop_table('available_investments')
    # ### end Alembic commands ###
