"""rename updates_and_features table

Revision ID: 368f306b6669
Revises: 8a6d5dd8858b
Create Date: 2024-04-29 16:03:04.615839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "368f306b6669"
down_revision: Union[str, None] = "8a6d5dd8858b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("updates_and_features", "manager_updates_and_features")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("manager_updates_and_features", "updates_and_features")
    # ### end Alembic commands ###
