"""transactions and chama table

Revision ID: 42ef2c9c3df7
Revises: 4cf889d3863c
Create Date: 2024-02-29 13:13:04.591140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ef2c9c3df7'
down_revision: Union[str, None] = '4cf889d3863c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamaname', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamas_chamaname'), 'chamas', ['chamaname'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chama',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chama')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_chamas_chamaname'), table_name='chamas')
    op.drop_table('chamas')
    # ### end Alembic commands ###
