"""add completed transaction column to wallet transactions

Revision ID: 506c77a9b5d9
Revises: 6d198ae17f78
Create Date: 2024-04-18 12:28:24.180993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506c77a9b5d9'
down_revision: Union[str, None] = '6d198ae17f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('transaction_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'transaction_completed')
    # ### end Alembic commands ###
