"""shares column added to the members_chamas association table

Revision ID: 50d3e2221226
Revises: f0a55a019de1
Create Date: 2024-04-15 09:50:07.457153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d3e2221226'
down_revision: Union[str, None] = 'f0a55a019de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members_chamas', 'num_of_shares',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members_chamas', 'num_of_shares',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
