"""profile update details

Revision ID: 570ca6bd3071
Revises: 17607b832ff3
Create Date: 2024-04-25 09:49:03.120842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570ca6bd3071'
down_revision: Union[str, None] = '17607b832ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_completed', sa.Boolean(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('transaction_destination', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.add_column('managers', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('managers', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('managers', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('managers', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('members', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('members', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('members', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('members', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'linkedin')
    op.drop_column('members', 'facebook')
    op.drop_column('members', 'twitter')
    op.drop_column('members', 'phone')
    op.drop_column('managers', 'linkedin')
    op.drop_column('managers', 'facebook')
    op.drop_column('managers', 'twitter')
    op.drop_column('managers', 'phone')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
