"""unique chama names

Revision ID: 5c84a5724d05
Revises: 1a2b88ac3200
Create Date: 2024-03-14 08:15:10.012642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c84a5724d05'
down_revision: Union[str, None] = '1a2b88ac3200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chamas_chama_name', table_name='chamas')
    op.create_index(op.f('ix_chamas_chama_name'), 'chamas', ['chama_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chamas_chama_name'), table_name='chamas')
    op.create_index('ix_chamas_chama_name', 'chamas', ['chama_name'], unique=False)
    # ### end Alembic commands ###
