"""wallets to members, transaction origin, and contribution day table

Revision ID: 5d72fec8506f
Revises: 569f3461f673
Create Date: 2024-04-16 10:59:56.124994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d72fec8506f'
down_revision: Union[str, None] = '569f3461f673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
