"""updated columns for investment performance

Revision ID: 5fea22f33208
Revises: c60f45dfea14
Create Date: 2024-04-25 15:28:07.252064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fea22f33208'
down_revision: Union[str, None] = 'c60f45dfea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments_performance', sa.Column('total_interest_earned', sa.Float(), nullable=True))
    op.add_column('investments_performance', sa.Column('weekly_interest', sa.Float(), nullable=True))
    op.add_column('investments_performance', sa.Column('Daily_interest', sa.Float(), nullable=True))
    op.add_column('investments_performance', sa.Column('monthly_interest', sa.Float(), nullable=True))
    op.drop_column('investments_performance', 'interest_earned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments_performance', sa.Column('interest_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('investments_performance', 'monthly_interest')
    op.drop_column('investments_performance', 'Daily_interest')
    op.drop_column('investments_performance', 'weekly_interest')
    op.drop_column('investments_performance', 'total_interest_earned')
    # ### end Alembic commands ###
