"""fix chama accounts cascade with chama

Revision ID: 63f3cfcf7f5b
Revises: e0973e928523
Create Date: 2024-06-28 08:50:53.065426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f3cfcf7f5b'
down_revision: Union[str, None] = 'e0973e928523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
