"""on cascade with chama-chamacontributionday

Revision ID: 6505394785eb
Revises: 8ea945271ec6
Create Date: 2024-06-14 09:09:46.063050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6505394785eb'
down_revision: Union[str, None] = '8ea945271ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chama_contribution_day_chama_id_fkey', 'chama_contribution_day', type_='foreignkey')
    op.create_foreign_key(None, 'chama_contribution_day', 'chamas', ['chama_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chama_contribution_day', type_='foreignkey')
    op.create_foreign_key('chama_contribution_day_chama_id_fkey', 'chama_contribution_day', 'chamas', ['chama_id'], ['id'])
    # ### end Alembic commands ###
