"""paybill changed status

Revision ID: 6942a0359d71
Revises: 01dc0d66896d
Create Date: 2024-05-14 14:01:46.990949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6942a0359d71'
down_revision: Union[str, None] = '01dc0d66896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamas', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamas', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
