"""features nad updates table added

Revision ID: 6b4889137742
Revises: b9bf9df0e992
Create Date: 2024-04-29 14:16:01.291213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4889137742'
down_revision: Union[str, None] = 'b9bf9df0e992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updates_and_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('feature_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updates_and_features_id'), 'updates_and_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updates_and_features_id'), table_name='updates_and_features')
    op.drop_table('updates_and_features')
    # ### end Alembic commands ###
