"""password in manager

Revision ID: 7101f5df5a78
Revises: fc157fd3ab14
Create Date: 2024-03-10 08:56:12.169643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7101f5df5a78'
down_revision: Union[str, None] = 'fc157fd3ab14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'password')
    # ### end Alembic commands ###
