"""chama description limited to 500 characters

Revision ID: 7a45b3b6352d
Revises: 9d67bbd09ac1
Create Date: 2024-05-14 11:24:24.560078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a45b3b6352d'
down_revision: Union[str, None] = '9d67bbd09ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
