"""phone number title update

Revision ID: 7e90f48c0dc3
Revises: 570ca6bd3071
Create Date: 2024-04-25 10:41:29.880147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e90f48c0dc3'
down_revision: Union[str, None] = '570ca6bd3071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('phone_number', sa.String(length=12), nullable=True))
    op.drop_column('managers', 'phone')
    op.add_column('members', sa.Column('phone_number', sa.String(length=12), nullable=True))
    op.drop_column('members', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_column('members', 'phone_number')
    op.add_column('managers', sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_column('managers', 'phone_number')
    # ### end Alembic commands ###
