"""nairobi time zone

Revision ID: 812462dab9ef
Revises: d0a6e56c9237
Create Date: 2024-07-16 19:16:26.471659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812462dab9ef'
down_revision: Union[str, None] = 'd0a6e56c9237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chamas_contribution_amount'), 'chamas', ['contribution_amount'], unique=False)
    op.create_index(op.f('ix_chamas_fine_per_share'), 'chamas', ['fine_per_share'], unique=False)
    op.create_index(op.f('ix_members_chamas_chama_id'), 'members_chamas', ['chama_id'], unique=False)
    op.create_index(op.f('ix_members_chamas_member_id'), 'members_chamas', ['member_id'], unique=False)
    op.create_index(op.f('ix_members_chamas_num_of_shares'), 'members_chamas', ['num_of_shares'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_chamas_num_of_shares'), table_name='members_chamas')
    op.drop_index(op.f('ix_members_chamas_member_id'), table_name='members_chamas')
    op.drop_index(op.f('ix_members_chamas_chama_id'), table_name='members_chamas')
    op.drop_index(op.f('ix_chamas_fine_per_share'), table_name='chamas')
    op.drop_index(op.f('ix_chamas_contribution_amount'), table_name='chamas')
    # ### end Alembic commands ###
