"""updating member chmas association table

Revision ID: 81dbdb07cbac
Revises: 55ff5bcad67d
Create Date: 2024-07-05 09:13:30.093148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dbdb07cbac'
down_revision: Union[str, None] = '55ff5bcad67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members_chamas', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.add_column('members_chamas', sa.Column('registration_fee_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members_chamas', 'registration_fee_paid')
    op.drop_column('members_chamas', 'date_joined')
    # ### end Alembic commands ###
