"""newsletter table

Revision ID: 8ea945271ec6
Revises: 4be2a36d19cf
Create Date: 2024-06-13 10:37:16.160732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea945271ec6'
down_revision: Union[str, None] = '4be2a36d19cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date_subscribed', sa.DateTime(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('date_unsubscribed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscriptions_id'), 'newsletter_subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subscriptions_id'), table_name='newsletter_subscriptions')
    op.drop_table('newsletter_subscriptions')
    # ### end Alembic commands ###
