"""added two columns to chama table

Revision ID: 91006a5a83b5
Revises: 6942a0359d71
Create Date: 2024-05-16 06:29:43.644482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91006a5a83b5'
down_revision: Union[str, None] = '6942a0359d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamas', sa.Column('category', sa.String(), nullable=True))
    op.add_column('chamas', sa.Column('fine_per_share', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamas', 'fine_per_share')
    op.drop_column('chamas', 'category')
    # ### end Alembic commands ###
