"""total paymnet expected with fines

Revision ID: 98622185b67c
Revises: 21b1accd3174
Create Date: 2024-06-19 08:03:16.929688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98622185b67c'
down_revision: Union[str, None] = '21b1accd3174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chama_withdrawals_id', table_name='chama_mmf_withdrawals')
    op.create_index(op.f('ix_chama_mmf_withdrawals_id'), 'chama_mmf_withdrawals', ['id'], unique=False)
    op.add_column('fines', sa.Column('total_expected_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fines', 'total_expected_amount')
    op.drop_index(op.f('ix_chama_mmf_withdrawals_id'), table_name='chama_mmf_withdrawals')
    op.create_index('ix_chama_withdrawals_id', 'chama_mmf_withdrawals', ['id'], unique=False)
    # ### end Alembic commands ###
