"""chama_blog to about_chama

Revision ID: 9d67bbd09ac1
Revises: 74e6b0fe646b
Create Date: 2024-05-14 08:33:31.182044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d67bbd09ac1'
down_revision: Union[str, None] = '74e6b0fe646b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_chama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('paybill_account_number', sa.Integer(), nullable=False),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('mission', sa.String(length=500), nullable=True),
    sa.Column('vision', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_chama_id'), 'about_chama', ['id'], unique=False)
    op.drop_index('ix_chama_blog_id', table_name='chama_blog')
    op.drop_table('chama_blog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chama_blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chama_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paybill_account_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('twitter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('facebook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mission', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('vision', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name='chama_blog_chama_id_fkey'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name='chama_blog_manager_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chama_blog_pkey')
    )
    op.create_index('ix_chama_blog_id', 'chama_blog', ['id'], unique=False)
    op.drop_index(op.f('ix_about_chama_id'), table_name='about_chama')
    op.drop_table('about_chama')
    # ### end Alembic commands ###
