"""contribution day

Revision ID: a1166a2d2eda
Revises: 927dda5672ef
Create Date: 2024-04-02 13:20:05.443379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1166a2d2eda'
down_revision: Union[str, None] = '927dda5672ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamas', sa.Column('contribution_day', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamas', 'contribution_day')
    # ### end Alembic commands ###
