"""added total amount invested to monthly interested

Revision ID: b9bf9df0e992
Revises: ff9213ea2fd8
Create Date: 2024-04-29 11:46:34.154020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bf9df0e992'
down_revision: Union[str, None] = 'ff9213ea2fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_mmf_interest', sa.Column('total_amount_invested', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_mmf_interest', 'total_amount_invested')
    # ### end Alembic commands ###
