"""remove the status column from accounts

Revision ID: c3eeeeae21d4
Revises: 2c3368612087
Create Date: 2024-04-04 07:18:29.530664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eeeeae21d4'
down_revision: Union[str, None] = '2c3368612087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chama_accounts', 'account_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chama_accounts', sa.Column('account_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
