"""update investments table name to available_investments

Revision ID: c60f45dfea14
Revises: 7e90f48c0dc3
Create Date: 2024-04-25 15:12:26.834890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60f45dfea14'
down_revision: Union[str, None] = '7e90f48c0dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_name', sa.String(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('min_invest_amount', sa.Integer(), nullable=False),
    sa.Column('investment_period', sa.Integer(), nullable=False),
    sa.Column('investment_period_unit', sa.String(), nullable=False),
    sa.Column('investment_rate', sa.Float(), nullable=False),
    sa.Column('investment_start_date', sa.DateTime(), nullable=True),
    sa.Column('investment_return', sa.Float(), nullable=False),
    sa.Column('investment_returned', sa.Boolean(), nullable=True),
    sa.Column('investment_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_investments_id'), 'available_investments', ['id'], unique=False)
    op.add_column('chama_investment', sa.Column('available_investment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chama_investment', 'available_investments', ['available_investment_id'], ['id'])
    op.drop_column('chama_investment', 'investment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chama_investment', sa.Column('investment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chama_investment', type_='foreignkey')
    op.drop_column('chama_investment', 'available_investment_id')
    op.drop_index(op.f('ix_available_investments_id'), table_name='available_investments')
    op.drop_table('available_investments')
    # ### end Alembic commands ###
