"""update on callback data

Revision ID: cbd329165867
Revises: 81dbdb07cbac
Create Date: 2024-07-05 10:04:44.527177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbd329165867"
down_revision: Union[str, None] = "81dbdb07cbac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "callback_data",
        sa.Column("Purpose", sa.String(), nullable=True, server_default="chama"),
    )
    op.add_column(
        "callback_data",
        sa.Column("Status", sa.String(), nullable=True, server_default="Pending"),
    )

    op.alter_column("callback_data", "Purpose", nullable=False, server_default=None)
    op.alter_column("callback_data", "Status", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("callback_data", "Status")
    op.drop_column("callback_data", "Purpose")
    # ### end Alembic commands ###
