"""daily column update

Revision ID: cd4306dade46
Revises: 5fea22f33208
Create Date: 2024-04-25 15:32:49.439610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4306dade46'
down_revision: Union[str, None] = '5fea22f33208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments_performance', sa.Column('daily_interest', sa.Float(), nullable=True))
    op.drop_column('investments_performance', 'Daily_interest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments_performance', sa.Column('Daily_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('investments_performance', 'daily_interest')
    # ### end Alembic commands ###
