"""unique constraint on member chamas

Revision ID: d0a6e56c9237
Revises: 80041faa8c3b
Create Date: 2024-07-05 13:09:34.366173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a6e56c9237'
down_revision: Union[str, None] = '80041faa8c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members_chamas', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('members_chamas', 'chama_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_member_chama', 'members_chamas', ['member_id', 'chama_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_member_chama', 'members_chamas', type_='unique')
    op.alter_column('members_chamas', 'chama_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('members_chamas', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
