"""chama accounts cascade with chama

Revision ID: e0973e928523
Revises: ed379890cdfc
Create Date: 2024-06-28 08:47:18.780061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0973e928523'
down_revision: Union[str, None] = 'ed379890cdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chama_accounts_chama_id_fkey', 'chama_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'chama_accounts', 'chamas', ['chama_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chama_accounts', type_='foreignkey')
    op.create_foreign_key('chama_accounts_chama_id_fkey', 'chama_accounts', 'chamas', ['chama_id'], ['id'])
    # ### end Alembic commands ###
