"""role check

Revision ID: fc157fd3ab14
Revises: a990ec39bfd8
Create Date: 2024-03-07 16:10:29.269249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc157fd3ab14'
down_revision: Union[str, None] = 'a990ec39bfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('is_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_member')
    op.drop_column('managers', 'is_manager')
    # ### end Alembic commands ###
