"""daily and monthly interest tracker added

Revision ID: ff9213ea2fd8
Revises: 7a2962df74de
Create Date: 2024-04-29 10:27:51.039737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9213ea2fd8'
down_revision: Union[str, None] = '7a2962df74de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mmf_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('date_earned', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_mmf_interest_id'), 'daily_mmf_interest', ['id'], unique=False)
    op.create_table('monthly_mmf_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_mmf_interest_id'), 'monthly_mmf_interest', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_mmf_interest_id'), table_name='monthly_mmf_interest')
    op.drop_table('monthly_mmf_interest')
    op.drop_index(op.f('ix_daily_mmf_interest_id'), table_name='daily_mmf_interest')
    op.drop_table('daily_mmf_interest')
    # ### end Alembic commands ###
