from django.urls import path

from . import views

app_name = "member"

urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path(
        "invite/<str:invite_to>/<str:name>/<int:id>",
        views.process_invite,
        name="invite",
    ),
    path(
        "change_password/<int:user_id>", views.change_password, name="change_password"
    ),
    path("get_chama_view/<int:chama_id>", views.get_chama_view, name="get_chama_view"),
    path(
        "access_chama/<str:chamaname>/<int:chama_id>",
        views.access_chama,
        name="access_chama",
    ),
    path(
        "activities/<str:chama_name>/<int:chama_id>/<str:activity_type>/<int:activity_id>",
        views.access_activity,
        name="activities",
    ),
    path("chama/<int:chamaid>", views.view_chama, name="chama"),
    path(
        "view_private_chama/<int:chamaid>/",
        views.view_private_chama,
        name="view_private_chama",
    ),
    path(
        "members_tracker/<str:chama_name>",
        views.members_tracker,
        name="members_tracker",
    ),
    path(
        "fines_tracker/<str:chama_name>/<int:chama_id>/<str:activity_name>/<int:activity_id>",
        views.fines_tracker,
        name="fines_tracker",
    ),
    path(
        "view_activity_members/<str:activity_name>/<int:activity_id>",
        views.view_activity_members,
        name="view_activity_members",
    ),
    path(
        "view_chama_members/<str:chama_name>/<int:chama_id>",
        views.view_chama_members,
        name="view_chama_members",
    ),
    path(
        "chama_activities/<str:chama_name>/<int:chama_id>",
        views.chama_activities,
        name="chama_activities",
    ),
    path(
        "get_about_chama/<str:chama_name>/<int:chama_id>",
        views.get_about_chama,
        name="get_about_chama",
    ),
    path(
        "get_about_activity/<str:activity_name>/<int:activity_id>",
        views.get_about_activity,
        name="get_about_activity",
    ),
    path(
        "activate_auto_contributions/<str:activity_name>/<int:activity_id>",
        views.activate_auto_contributions,
        name="activate_auto_contributions",
    ),
    path(
        "deactivate_auto_contributions/<str:activity_name>/<int:activity_id>",
        views.deactivate_auto_contributions,
        name="deactivate_auto_contributions",
    ),
    path(
        "update_profile_image",
        views.update_profile_image,
        name="update_profile_image",
    ),
    path(
        "update_phone_number/<int:user_id>",
        views.update_phone_number,
        name="update_phone_number",
    ),
    path(
        "update_twitter_handle/<int:user_id>",
        views.update_twitter_handle,
        name="update_twitter_handle",
    ),
    path(
        "update_linkedin_handle/<int:user_id>",
        views.update_linkedin_handle,
        name="update_linkedin_handle",
    ),
    path(
        "update_facebook_handle/<int:user_id>",
        views.update_facebook_handle,
        name="update_facebook_handle",
    ),
    path("join", views.join_chama, name="join"),
    path(
        "join_activity/<str:chama_name>/<int:activity_id>",
        views.join_activity,
        name="join_activity",
    ),
    path(
        "from_wallet_to_activity/<str:chama_name>/<int:chama_id>/<str:activity_type>/<int:activity_id>",
        views.from_wallet_to_activity,
        name="from_wallet_to_activity",
    ),
    path(
        "from_wallet_to_select_activity/<int:chama_id>/<str:chama_name>",
        views.from_wallet_to_select_activity,
        name="from_wallet_to_select_activity",
    ),
    path("wallet_transactions", views.wallet_transactions, name="wallet_transactions"),
    path(
        "fix_mpesa_to_wallet_deposit",
        views.fix_mpesa_to_wallet_deposit,
        name="fix_mpesa_to_wallet_deposit",
    ),
    path(
        "rotation_contributions/<int:activity_id>",
        views.rotation_contributions,
        name="rotation_contributions",
    ),
    path(
        "get_increase_shares_page/<int:activity_id>",
        views.get_increase_shares_page,
        name="get_increase_shares_page",
    ),
    path(
        "increase_shares/<int:activity_id>",
        views.increase_shares,
        name="increase_shares",
    ),
    path(
        "get_late_joining_activity_page/<int:activity_id>",
        views.get_late_joining_activity_page,
        name="get_late_joining_activity_page",
    ),
    path(
        "join_activity_late/<int:activity_id>",
        views.join_activity_late,
        name="join_activity_late",
    ),
    path(
        "get_disbursement_records/<int:activity_id>",
        views.get_disbursement_records,
        name="get_disbursement_records",
    ),
]
